### ISSUE TITLE
Should defflow be called state-flow/deftest?

### ISSUE THREAD

**Issue by rafaelzlisboa** [nubank/state-flow#111]
One of the things I found a bit confusing when starting on state-flow was the fact that you do a `defflow` and inside there's a `flow` definition. My initial expectation was that they would be like `defn` and `fn` - essentially defining the same thing.

Since defflow is defining a clojure.test that runs a flow, should we call it `deftest`?

**Comment by dchelimsky** [comment]
> That would also solve the particular problem of cider being able to find the tests: https://github.com/nubank/state-flow#tooling

That link offers a solution to the problem ;)

What if you want to mix clojure.test tests with state-flow in the same namespace? clojure.test.check deals with this problem with a different name because the thing it's making is not the same thing that `deftest` makes. I'm not totally against this idea, but there are tradeoffs to consider, so let's not jump in and do it.

**Comment by dchelimsky** [comment]
Actually, `defflow` does not require a nested `flow`. This works fine:

```clojure
(defflow addition-adds-numbers
  {:init (constantly {:n 0})}
  (state/modify update :n + 2)
  (match? 2 (state/gets :n)))
```

And then the custom `defflow`  you write in your app looks the same, but without the params:

```clojure
(defflow addition-adds-numbers
  (state/modify update :n + 2)
  (match? 2 (state/gets :n)))
```

**Comment by dchelimsky** [comment]
See: https://github.com/nubank/state-flow#clojuretest-and-matcher-combinators (though there are examples further down the doc that have unnecessary nested flows).

**Comment by dchelimsky** [comment]
@rafaelzlisboa can we close this now?

**Comment by dchelimsky** [comment]
Closing this. @rafaelzlisboa please reopen if you want to revisit it.
